[tool.black]
line-length = 88
target-version = ["py39"]

[tool.ruff]
line-length = 88
src = ["pogo_analyzer", "."]
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
